version: '3.9'
services:
  mongodb:
    ports:
      - 27017:27017
    image: mongo:6.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - dictionary_api_network

  backend:
    tty: true
    # uncomment if you need to exec something in container as root
    # user: root
    stdin_open: true
    ports:
      - 8000:8000
    build:
      context: .
      args:
        - REQUIREMENTS_FILE=base.txt
    image: dictionary-api-backend-dev
    depends_on:
      - mongodb
    # Project data is already copied to the docker container. Uncomment for
    # development purposes to avoid rebuilding docker image every time for each
    # change in the code.
    # volumes:
    #   - .:/app/
    networks:
      - dictionary_api_network
    env_file:
      - .docker.base.env

  tests:
    tty: true
    user: root
    stdin_open: true
    build:
      context: .
      args:
        - REQUIREMENTS_FILE=test.txt
    image: dictionary-api-backend-test
    depends_on:
      - mongodb
    # Project data is already copied to the docker container. Uncomment for
    # development purposes to avoid rebuilding docker image every time for each
    # change in the code.
    # volumes:
    #   - .:/app/
    networks:
      - dictionary_api_network
    command: pytest
    env_file:
      - .docker.base.env

networks:
  dictionary_api_network:

volumes:
  mongo_data:
