version: '3.9'
services:
  mongodb:
    ports:
      - 27017:27017
    image: mongo:6.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - dictionary_api_network

  backend:
    tty: true
    # uncomment if you need to exec something in container as root
    # user: root
    stdin_open: true
    ports:
      - 8000:8000
    build:
      context: .
    image: dictionary-api-backend-dev
    depends_on:
      - mongodb
    volumes:
      - .:/app:cached
    networks:
      - dictionary_api_network
    command: uvicorn app.main:app --host=0.0.0.0 --port=8000 --reload
    env_file:
      - .docker.base.env

  tests:
    tty: true
    user: root
    stdin_open: true
    build:
      context: .
    image: dictionary-api-backend-test
    depends_on:
      - mongodb
    volumes:
      - .:/app:cached
    networks:
      - dictionary_api_network
    command: pytest
    env_file:
      - .docker.base.env

networks:
  dictionary_api_network:

volumes:
  mongo_data:
