"""init migration

Revision ID: 7cede735e392
Revises: 
Create Date: 2023-01-30 06:05:55.266582

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op


# revision identifiers, used by Alembic.
revision = '7cede735e392'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=256), nullable=True),
    sa.Column('examples', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('translations', postgresql.JSON(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('definitions', postgresql.JSON(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_id'), 'word', ['id'], unique=False)
    op.create_index(op.f('ix_word_word'), 'word', ['word'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_word_word'), table_name='word')
    op.drop_index(op.f('ix_word_id'), table_name='word')
    op.drop_table('word')
    # ### end Alembic commands ###
